name: Deploy SAM Application

on:
  push:
    branches:
      - master

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Build with Maven
        run: mvn package
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Install or Update SAM CLI
        run: |
          curl -L https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip -o sam.zip
          unzip sam.zip -d sam-installation
          if [ -d "/usr/local/aws-sam-cli" ]; then
            echo "Existing SAM CLI found, updating..."
            sudo ./sam-installation/install --update
          else
            echo "No existing SAM CLI, installing fresh..."
            sudo ./sam-installation/install
          fi
          sam --version
      - name: Deploy SAM Application (Dev)
        run: |
          sam deploy --stack-name s3-lambda-sns-dev \
            --template-file template.yaml \
            --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
            --region ${{ secrets.AWS_REGION }} \
            --parameter-overrides Environment=dev SNSSubscriptionEmail=${{ secrets.DEV_SNS_EMAIL }} \
            --no-fail-on-empty-changeset

  deploy-prod:
    runs-on: ubuntu-latest
    environment: prod
    needs: deploy-dev
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Build with Maven
        run: mvn package
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Install or Update SAM CLI
        run: |
          curl -L https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip -o sam.zip
          unzip sam.zip -d sam-installation
          if [ -d "/usr/local/aws-sam-cli" ]; then
            echo "Existing SAM CLI found, updating..."
            sudo ./sam-installation/install --update
          else
            echo "No existing SAM CLI, installing fresh..."
            sudo ./sam-installation/install
          fi
          sam --version
      - name: Deploy SAM Application (Prod)
        run: |
          sam deploy --stack-name s3-lambda-sns-prod \
            --template-file template.yaml \
            --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
            --region ${{ secrets.AWS_REGION }} \
            --parameter-overrides Environment=prod SNSSubscriptionEmail=${{ secrets.PROD_SNS_EMAIL }} \
            --no-fail-on-empty-changeset
