name: Deploy SAM Application

on:
  push:
    branches:
      - master
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Install SAM CLI
        run: |
          pip install aws-sam-cli

      - name: Build SAM Application
        run: |
          mvn clean package
          sam build

      - name: Deploy to Development
        if: github.ref == 'refs/heads/dev'
        run: |
          sam deploy \
            --stack-name weekeightlabdev \
            --parameter-overrides Environment=dev SNSSubscription=${{ secrets.DEV_SNS_EMAIL }} \
            --capabilities CAPABILITY_IAM \
            --no-fail-on-empty-changeset \
            --no-confirm-changeset \
            --region eu-central-1 \
            --resolve-s3

      - name: Deploy to Production
        if: github.ref == 'refs/heads/master'
        run: |
          sam deploy \
            --stack-name weekeightlabprod \
            --parameter-overrides Environment=prod SNSSubscription=${{ secrets.PROD_SNS_EMAIL }} \
            --capabilities CAPABILITY_IAM \
            --no-fail-on-empty-changeset \
            --no-confirm-changeset \
            --region eu-central-1 \
            --resolve-s3